"use strict"

module.exports = {
	INITIALIZE: 'INITIALIZE',
	CREATE_SUBSCRIPTION: 'CREATE_SUBSCRIPTION',
	UPDATE_SUBSCRIPTION: 'UPDATE_SUBSCRIPTION',
	DELETE_SUBSCRIPTION: 'DELETE_SUBSCRIPTION',
	SHARE_SUBSCRIPTION: 'SHARE_SUBSCRIPTION'
};